/* eslint-disable @typescript-eslint/ban-ts-comment */
import { FunctionComponent, useCallback } from 'react';
import update from 'react-addons-update';
import { useQuery } from '@apollo/react-hooks';

import { getPokemonListQuery } from '../queries/getPokemonList.query';
import { getPokemonList, getPokemonListVariables } from '../queries/types/getPokemonList';
import { PokemonListCard } from '../components/PokemonListCard';

const PAGINATION_PAGE_SIZE = 12;

const Index: FunctionComponent = () => {
  const { data, loading, fetchMore } = useQuery<getPokemonList, getPokemonListVariables>(
    getPokemonListQuery,
    {
      variables: {
        first: PAGINATION_PAGE_SIZE,
      },
    }
  );

  const handleLoadMore = useCallback(() => {
    const first = data?.pokemons?.first || PAGINATION_PAGE_SIZE;
    const offset = (data?.pokemons?.offset || 0) + PAGINATION_PAGE_SIZE;

    fetchMore({
      variables: { first, offset },
      updateQuery: (prev, { fetchMoreResult }) => {
        if (!fetchMoreResult) return prev;

        const newItems = fetchMoreResult?.pokemons?.items || [];
        const newOffset = fetchMoreResult?.pokemons?.offset || 0;
        // @ts-ignore: ts confused with types that generated by apollo
        const newPokemon = update(prev, {
          pokemons: {
            items: { $push: newItems },
            offset: { $set: newOffset },
          },
        });

        return newPokemon;
      },
    });
  }, [data, fetchMore]);

  return (
    <div className="max-w-screen-xl mx-auto">
      <PokemonListCard
        hasMore={true}
        onLoadMore={handleLoadMore}
        loading={loading}
        pokemons={data?.pokemons?.items || []}
      />
    </div>
  );
};

export default Index;
