/* eslint-disable @typescript-eslint/ban-ts-comment */
import { FunctionComponent, useCallback } from 'react';
import update from 'react-addons-update';
import { useQuery } from '@apollo/react-hooks';
import Head from 'next/head';

import { getPokemonListQuery } from '../queries/getPokemonList.query';
import { getPokemonList, getPokemonListVariables } from '../queries/types/getPokemonList';
import { PokemonListCard } from '../components/PokemonListCard';
import { Loader } from '../components/Loader';

const PAGINATION_PAGE_SIZE = 12;

const Index: FunctionComponent = () => {
  const { data, fetchMore } = useQuery<getPokemonList, getPokemonListVariables>(
    getPokemonListQuery,
    {
      variables: {
        first: PAGINATION_PAGE_SIZE,
      },
    }
  );

  const handleLoadMore = useCallback(() => {
    const nextOffset = data?.pokemons?.nextOffset;
    fetchMore({
      variables: { first: PAGINATION_PAGE_SIZE, offset: nextOffset },
      updateQuery: (prev, { fetchMoreResult }) => {
        if (!fetchMoreResult) return prev;

        const newItems = fetchMoreResult?.pokemons?.items || [];
        const newOffset = fetchMoreResult?.pokemons?.offset || 0;
        const newNextOffset = fetchMoreResult?.pokemons?.nextOffset || 0;
        // @ts-ignore: ts confused with types that generated by apollo
        const newPokemon = update(prev, {
          pokemons: {
            items: { $push: newItems },
            offset: { $set: newOffset },
            nextOffset: { $set: newNextOffset },
          },
        });

        return newPokemon;
      },
    });
  }, [data, fetchMore]);

  return (
    <div className="max-w-screen-xl mx-auto">
      <Head>
        <title>Pokedex</title>
      </Head>
      <header className="text-center mt-5">
        <h1 className="text-5xl font-bold">Pokedex</h1>
        <p className="text-xl font-bold text-gray-700">let&apos;s play pokemon!</p>
      </header>
      <PokemonListCard
        hasMore={!!data?.pokemons?.nextOffset}
        onLoadMore={handleLoadMore}
        pokemons={data?.pokemons?.items || []}
        loader={<Loader />}
      />
    </div>
  );
};

export default Index;
